name: "Install Python Dependencies"
description: "Reusable Python dependency installer"
inputs:
  python-version:
    description: "Python version"
    required: true
  tests-dir:
    description: "Tests directory"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      working-directory: ${{ inputs.tests-dir }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install allure-pytest
      shell: bash