name: Go CI with Security Scans (SAST)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '15 3 * * *' # 03:15 UTC
  workflow_dispatch:

jobs:
  build-and-sast:
    name: Build & SAST Scan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go-api-tests

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: go

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Check Formatting
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          echo "Go code is not formatted:"
          gofmt -l .
          exit 1
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      env:
        # Set OWM_API_KEY in repository secrets, or use a dummy value for forks/PRs
        OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      run: go test -v ./...

    - name: Perform CodeQL Analysis (SAST)
      uses: github/codeql-action/analyze@v3