name: Java Event-Driven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 4 * * *' # 04:00 UTC
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Build and Test
        working-directory: java-event-driven-tests
        run: mvn clean test -DsuiteXmlFile=testng-integration-suite.xml

      - name: Upload Surefire Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: java-event-driven-tests/target/surefire-reports
      - name: Java Report Download Instructions
        run: |
          echo "Download the 'surefire-reports' artifact from the Actions run and view the HTML report locally."
