name: Pact Contract Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install consumer dependencies
        working-directory: pact-contract-testing/consumer-frontend
        run: npm ci

      - name: Run consumer tests (generates pact)
        working-directory: pact-contract-testing/consumer-frontend
        run: npm test

      - name: Install provider dependencies
        working-directory: pact-contract-testing/provider-api
        run: npm ci

      - name: Run provider verification
        working-directory: pact-contract-testing/provider-api
        run: npm test