name: Pact Contract Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '30 4 * * *' # 04:30 UTC
  workflow_dispatch:

jobs:
  contract-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache npm (consumer)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-consumer-${{ runner.os }}-node18-${{ hashFiles('pact-contract-testing/consumer-frontend/package-lock.json') }}
          restore-keys: |
            npm-consumer-${{ runner.os }}-node18-

      - name: Install consumer dependencies
        working-directory: pact-contract-testing/consumer-frontend
        run: npm ci

      - name: Run consumer tests (generates pact)
        working-directory: pact-contract-testing/consumer-frontend
        run: npm test

      - name: Cache npm (provider)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-provider-${{ runner.os }}-node18-${{ hashFiles('pact-contract-testing/provider-api/package-lock.json') }}
          restore-keys: |
            npm-provider-${{ runner.os }}-node18-

      - name: Install provider dependencies
        working-directory: pact-contract-testing/provider-api
        run: npm ci

      - name: Run provider verification
        working-directory: pact-contract-testing/provider-api
        run: npm test

      - name: Upload Pact files as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pact-files
          path: |
            pact-contract-testing/consumer-frontend/pacts/
            pact-contract-testing/provider-api/pacts/
      - name: Pact Report Download Instructions
        run: |
          echo "Download the 'pact-files' artifact from the Actions run and view the files locally."
