name: Playwright TS CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        # This path has been updated
        working-directory: playwright-ts-api-test
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint --fix

      - name: Run Playwright tests
        run: npx playwright test --reporter=json,html

      - name: Upload Test Report (HTML)
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-ts-api-test/playwright-report
